2019-12-14 15:58:29,913 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-14 15:58:29,912 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-14 15:58:29,913 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-14 15:58:29,914 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-14 15:58:29,921 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-14 15:58:29,928 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-14 15:58:29,934 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-14 15:58:29,944 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-14 15:59:06,901 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment[0m
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
2019-12-14 15:59:06,901 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment[0m
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
2019-12-14 15:59:06,901 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment[0m
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
2019-12-14 15:59:06,901 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment[0m
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
2019-12-14 15:59:06,901 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment[0m
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
2019-12-14 15:59:06,901 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment[0m
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
2019-12-14 15:59:06,901 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment[0m
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
2019-12-14 15:59:06,901 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment[0m
Traceback (most recent call last):
  File "../tools/main.py", line 292, in <module>
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment
    logger(rank=-1).info("=> rank {} of {} jobs, in {}".format(
UnboundLocalError: local variable 'logger' referenced before assignment
12/14/19 15:59:07.154 (P3983406.T3983406) [I] parrots exit with unhandled error
12/14/19 15:59:07.155 (P3983408.T3983408) [I] parrots exit with unhandled error
12/14/19 15:59:07.154 (P3983413.T3983413) [I] parrots exit with unhandled error
12/14/19 15:59:07.154 (P3983407.T3983407) [I] parrots exit with unhandled error
12/14/19 15:59:07.154 (P3983409.T3983409) [I] parrots exit with unhandled error
12/14/19 15:59:07.155 (P3983410.T3983410) [I] parrots exit with unhandled error
12/14/19 15:59:07.155 (P3983411.T3983411) [I] parrots exit with unhandled error
12/14/19 15:59:07.154 (P3983412.T3983412) [I] parrots exit with unhandled error
srun: error: SH-IDC1-10-5-31-36: task 5: Exited with exit code 1
srun: error: SH-IDC1-10-5-31-36: tasks 0-1,3-4,6-7: Exited with exit code 1
srun: error: SH-IDC1-10-5-31-36: task 2: Exited with exit code 1
